version: '2'
services:
  jenkins:
    image: jenkins
    ports:
      - "89:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./jenkins/jenkins-data:/root
    networks:
      - net
    container_name: jenkins
networks:
  net:
    driver: bridge
