version: "3.3"

networks:
  service-network:
    driver: overlay
    attachable: true

services:
  redis:
    image: redis
    networks:
      - service-network
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    tty: true
    deploy:
      placement:
        constraints:
          - node.hostname == node-sub
