FROM setyourmindpark/debian-node6
MAINTAINER jaehunpark "setyourmindpark@gmail.com"

RUN apt-get update && \
    apt-get install -y vim && \
    apt-get install -y git-core && \
    npm install -y pm2 -g

EXPOSE 4000
VOLUME /root

CMD ["/bin/bash"]
