version: "3.5"

networks:
  net:
    external: true
    name: setyourmindpark_service_net

services:
  backend:
    image: setyourmindpark/debian-node:8
    ports:
      - 4000:4000
    environment:
      - TZ=Asia/Seoul
    networks:
      - net
    tty: true
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.type == backend